In [2]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot
import pypsa

python-dotenv could not parse statement starting at line 3
python-dotenv could not parse statement starting at line 4
python-dotenv could not parse statement starting at line 5
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/requests/__init__.py:113: RequestsDependencyWarning: urllib3 (2.3.0) or chardet (7.4.3)/charset_normalizer (3.4.1) doesn't match a supported version!
  warnings.warn(


#### Modeling a toy power grid as a graph

In [3]:
## power grid class 

class Bus:
    pass 

class Line: 
    pass 

class Grid: 
    pass 

In [4]:
## PTDF matrix

In [5]:
## LODF matrix

##### Shortcuts using the power modeling library PyPSA-USA 

In [17]:
n = pypsa.Network()

for i in range(1, 5):
    n.add("Bus", f"Bus {i}")

branches = [("Bus 1", "Bus 2"), ("Bus 2", "Bus 3"), ("Bus 3", "Bus 4"), ("Bus 4", "Bus 1")]
for idx, (b0, b1) in enumerate(branches, start=1):
    n.add("Line", f"Line {idx}", bus0=b0, bus1=b1, x=0.1, r=0.0)

n.determine_network_topology()

for sub_network in n.sub_networks.obj:
    sub_network.calculate_PTDF() 
    
    print(f"PTDF Matrix for {sub_network.name}:\n", sub_network.PTDF)

PTDF Matrix for 0:
 [[ 0.   -0.75 -0.5  -0.25]
 [ 0.    0.25 -0.5  -0.25]
 [ 0.    0.25  0.5  -0.25]
 [ 0.    0.25  0.5   0.75]]
